Revert bcc0cee (Debug view now displays used ev backend)
This commit broke the build for me:

include/np_event.h:30:1: error: conflicting types for '_np_event_get_loop_in'
NP_EVENT_EVLOOP_PROTOTYPE(in)
^
include/np_event.h:18:18: note: expanded from macro 'NP_EVENT_EVLOOP_PROTOTYPE'
struct ev_loop * _np_event_get_loop_##LOOPNAME(np_state_t *context);    \
                 ^
<scratch space>:117:1: note: expanded from here
_np_event_get_loop_in
^
examples/example_helper.c:1152:63: note: previous implicit declaration is here
src/neuropil.c:                        unsigned int ev_backends = ev_backend(_np_event_get_loop_in(context));